export const demoQcellObjProperty = {
  id: "qcell-demo",
  rowheaders: ["sequence"] as const,
  onechlikedit: true,
  columns: [
    { key: "id", title: ["ID"], width: "5%", type: "html" },
    { key: "name", title: ["이름"], width: "20%", type: "html" },
    { key: "role", title: ["역할"], width: "20%", type: "html" },
    { key: "active", title: ["활성"], width: "5%", type: "html" },
    { key: "actions", title: ["Actions"], width: "20%", type: "html" },
    { key: "createdAt", title: ["작성일"], width: "30%", type: "html" },
  ],
  pagination: {
    pageunit: 5,
    mode: "simple",
  },
  data: {
    input: [
      { id: 1, name: "Kim", role: "Admin", active: "Y", actions: "Edit", createdAt: "2026-01-01" },
      { id: 2, name: "Lee", role: "Editor", active: "Y", actions: "Edit", createdAt: "2026-01-01" },
      {
        id: 3,
        name: "Park",
        role: "Viewer",
        active: "N",
        actions: "Edit",
        createdAt: "2026-01-01",
      },
      {
        id: 4,
        name: "Choi",
        role: "Viewer",
        active: "N",
        actions: "Edit",
        createdAt: "2026-01-01",
      },
      {
        id: 5,
        name: "Kwon",
        role: "Viewer",
        active: "N",
        actions: "Edit",
        createdAt: "2026-01-01",
      },
      { id: 6, name: "Kim", role: "Viewer", active: "N", actions: "Edit", createdAt: "2026-01-01" },
      { id: 7, name: "Lee", role: "Viewer", active: "N", actions: "Edit", createdAt: "2026-01-01" },
      {
        id: 8,
        name: "Park",
        role: "Viewer",
        active: "N",
        actions: "Edit",
        createdAt: "2026-01-01",
      },
      {
        id: 9,
        name: "Choi",
        role: "Viewer",
        active: "N",
        actions: "Edit",
        createdAt: "2026-01-01",
      },
      {
        id: 10,
        name: "Kwon",
        role: "Viewer",
        active: "N",
        actions: "Edit",
        createdAt: "2026-01-01",
      },
    ],
  },
};
